# Generated by Django 3.1.1 on 2020-12-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='altura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
