# Generated by Django 3.1.1 on 2020-11-22 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('musclulo_primario', models.CharField(max_length=250)),
                ('musculos_secundarios', models.CharField(max_length=250)),
                ('video', models.URLField()),
                ('tipo', models.CharField(max_length=250)),
                ('equipamento', models.CharField(max_length=250)),
                ('instrucoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TerinoEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticao', models.IntegerField()),
                ('duracao', models.DurationField()),
                ('descanco', models.DurationField()),
                ('exercicio', models.ManyToManyField(to='pessonal.Exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('validade', models.DateTimeField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tereinoex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessonal.terinoex')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoCorporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('musculo_esqueletico', models.FloatField()),
                ('massa_muscular', models.FloatField()),
                ('massa_ossea', models.FloatField()),
                ('idade_corporal', models.IntegerField()),
                ('imc', models.FloatField()),
                ('gordura_corporal', models.FloatField()),
                ('gordura_visceral', models.IntegerField()),
                ('metabolismo_basal', models.IntegerField()),
                ('relacao_cintura_quadril', models.FloatField()),
                ('pressao_arterial', models.CharField(max_length=8)),
                ('frequencia_cardiaca', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
