# Generated by Django 3.1.1 on 2020-11-22 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaocorporal',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
