# Generated by Django 3.1.1 on 2020-11-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0002_composicaocorporal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaocorporal',
            name='observacao',
            field=models.TextField(default='nan'),
            preserve_default=False,
        ),
    ]
