# Generated by Django 3.1.1 on 2020-11-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0003_composicaocorporal_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='tereinoex',
        ),
        migrations.AddField(
            model_name='terinoex',
            name='treino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pessonal.treino'),
            preserve_default=False,
        ),
    ]
