# Generated by Django 3.1.1 on 2020-11-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0004_auto_20201122_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TerinoEx',
            new_name='TreinoEx',
        ),
    ]
