# Generated by Django 3.1.1 on 2020-11-22 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0005_auto_20201122_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinoex',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='treinoex',
            name='exercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pessonal.exercicio'),
            preserve_default=False,
        ),
    ]
