# Generated by Django 3.1.1 on 2020-11-24 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0006_auto_20201122_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='validade',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
