# Generated by Django 3.1.1 on 2020-11-25 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessonal', '0007_auto_20201123_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pescoco', models.FloatField()),
                ('ombros', models.FloatField()),
                ('torax', models.FloatField()),
                ('abdmen', models.FloatField()),
                ('quadril', models.FloatField()),
                ('cintura', models.FloatField()),
                ('braco_esquerdo', models.FloatField()),
                ('braco_esquerdo_c', models.FloatField()),
                ('braco_direito', models.FloatField()),
                ('braco_direito_c', models.FloatField()),
                ('perna_esquerda_m', models.FloatField()),
                ('perna_esquerda_d', models.FloatField()),
                ('perna_esquerda_p', models.FloatField()),
                ('perna_direita_m', models.FloatField()),
                ('perna_direita_d', models.FloatField()),
                ('perna_direita_p', models.FloatField()),
                ('panturrilha_esquerda', models.FloatField()),
                ('panturrilha_direita', models.FloatField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
