# Generated by Django 3.1.1 on 2020-12-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0008_medidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinoex',
            name='duracao',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='treinoex',
            name='repeticao',
            field=models.IntegerField(null=True),
        ),
    ]
