# Generated by Django 3.1.1 on 2020-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0009_auto_20201212_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinoex',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treinoex',
            name='repeticao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
