# Generated by Django 3.1.1 on 2021-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0010_auto_20201212_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='video',
            field=models.CharField(max_length=250),
        ),
    ]
