# Generated by Django 3.1.1 on 2021-02-12 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessonal', '0012_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='aluno',
        ),
        migrations.AddField(
            model_name='treino',
            name='aluno',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
