# Generated by Django 3.1.1 on 2021-02-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0013_auto_20210212_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
