# Generated by Django 3.1.1 on 2021-03-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessonal', '0016_auto_20210314_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='musclulo_primario',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='musclulo_primario',
            field=models.ManyToManyField(related_name='principal', to='pessonal.Musculos'),
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='musculos_secundarios',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='musculos_secundarios',
            field=models.ManyToManyField(related_name='secundario', to='pessonal.Musculos'),
        ),
    ]
